alias switch := rebuild

ip := "192.168.1.100"

check:
  nix flake check --impure

update:
  nix flake update --impure

build:
  nixos-rebuild build --flake .#vhost-dev --target-host root@{{ip}} --impure

deploy:
  # todo: issue a wipe warning...
  nix run github:nix-community/nixos-anywhere -- --flake .#vhost-dev root@{{ip}} -i ~/.ssh/id_cim_thecowboyai

test:
  # run tests on the remote installation

rebuild:
  nixos-rebuild switch --flake .#vhost-dev --target-host root@{{ip}} --impure

format:
  alejandra .

graph:
  # warning... this takes about 10 minutes to generate
  nix build .#nixosConfigurations.vhost-dev.config.system.build.toplevel --impure
  nix-store --query --graph ./result | dot -Tsvg > graph.svg
